### ISSUE TITLE
Problem with 1.0.5

### ISSUE THREAD

**Issue by xmorpher** [ipsilondev/openfl-unityads#3]
I get this error in the compiler when i upgrade all the libraries to the latests in haxelib
## (and openfl-unityads 1.0.5)

-post-compile:

-obfuscate:
   [delete] Deleting: D:\MY_PROJECT\bin\android\bin\deps\openfl_unityads\bin\proguard\original.jar
   [delete] Deleting: D:\MY_PROJECT\bin\android\bin\deps\openfl_unityads\bin\proguard\obfuscated.jar
      [jar] Building jar: D:\MY_PROJECT\bin\android\bin\deps\openfl_unityads\bin\proguard\original.jar
 [proguard] ProGuard, version 4.7
 [proguard] Reading input...
 [proguard] Reading program jar [D:\MY_PROJECT\bin\android\bin\deps\openfl_unityads\bin\proguard\original.jar]
 [proguard] Reading program jar [D:\MY_PROJECT\bin\android\bin\deps\extension-api\bin\classes.jar]
 [proguard] Reading program jar [D:\MY_PROJECT\bin\android\bin\deps\openfl_unityads\libs\unity-ads.jar]
 [proguard] Note: duplicate definition of program class [com.unity3d.ads.android.BuildConfig]
 [proguard] Reading library jar [C:\Development\Android_SDK\platforms\android-17\android.jar]
 [proguard] Note: there were 1 duplicate class definitions.
 [proguard] Initializing...
 [proguard] Note: com.unity3d.ads.android.data.UnityAdsAdvertisingId: can't find dynamically referenced class com.google.android.gms.common.GooglePlayServicesUtil
 [proguard] Note: com.unity3d.ads.android.data.UnityAdsAdvertisingId: can't find dynamically referenced class com.google.android.gms.ads.identifier.AdvertisingIdClient
 [proguard] Note: com.unity3d.ads.android.data.UnityAdsAdvertisingId: can't find dynamically referenced class com.google.android.gms.ads.identifier.AdvertisingIdClient$Info
 [proguard] Note: com.unity3d.ads.android.unity3d.UnityAdsUnityWrapper: can't find dynamically referenced class com.unity3d.player.UnityPlayer
 [proguard] Note: the configuration refers to the unknown class 'com.google.vending.licensing.ILicensingService'
 [proguard] Note: the configuration refers to the unknown class 'com.android.vending.licensing.ILicensingService'
 [proguard] Note: the configuration refers to the unknown class 'com.android.vending.licensing.ILicensingService'
 [proguard] Note: the configuration refers to the unknown class 'com.applifier.impact.android.ApplifierImpact'
 [proguard] Note: the configuration refers to the unknown class 'com.applifier.impact.android.ApplifierImpact'
 [proguard] Note: the configuration refers to the unknown class 'com.applifier.impact.android.IApplifierImpactListener'
 [proguard] Note: the configuration refers to the unknown class 'com.applifier.impact.android.IApplifierImpactListener'
 [proguard] Note: the configuration refers to the unknown class 'com.unity3d.ads.android.view.UnityAdsMainView$UnityAdsMainViewAction'
 [proguard] Note: the configuration refers to the unknown class 'Object'
 [proguard]       Maybe you meant the fully qualified name 'java.lang.Object'?
 [proguard] Note: the configuration refers to the unknown class 'com.google.android.gms.common.internal.safeparcel.SafeParcelable'
 [proguard] Note: the configuration refers to the unknown class 'com.google.android.gms.common.annotation.KeepName'
 [proguard] Note: the configuration refers to the unknown class 'com.google.android.gms.common.annotation.KeepName'
 [proguard] Note: the configuration refers to the unknown class 'com.google.android.gms.common.annotation.KeepName'
 [proguard] Note: the configuration keeps the entry point 'com.unity3d.ads.android.webapp.i { i(com.unity3d.ads.android.webapp.k); }', but not the descriptor class 'com.unity3d.ads.android.webapp.k'
 [proguard] Note: the configuration keeps the entry point 'com.unity3d.ads.android.webapp.k { k(java.lang.String,java.lang.String,java.lang.String,com.unity3d.ads.android.webapp.j,int); }', but not the descriptor class 'com.unity3d.ads.android.webapp.j'
 [proguard] Note: the configuration keeps the entry point 'com.unity3d.ads.android.webapp.l { l(java.lang.String,java.lang.String,java.lang.String,com.unity3d.ads.android.webapp.j,int); }', but not the descriptor class 'com.unity3d.ads.android.webapp.j'
 [proguard] Note: there were 13 references to unknown classes.
 [proguard]       You should check your configuration for typos.
 [proguard] Note: there were 3 unkept descriptor classes in kept class members.
 [proguard]       You should consider explicitly keeping the mentioned classes
 [proguard](using).
 [proguard] Note: there were 4 unresolved dynamic references to classes or interfaces.
 [proguard]       You should check if you need to specify additional program jars.
 [proguard] Ignoring unused library classes...
 [proguard]   Original number of library classes: 3259
 [proguard]   Final number of library classes:    450
 [proguard] Printing kept classes, fields, and methods...
 [proguard] Shrinking...
 [proguard] Printing usage to [D:\MY_PROJECT\bin\android\bin\deps\openfl_unityads\bin\proguard\usage.txt]...
 [proguard] Removing unused program classes and class elements...
 [proguard]   Original number of program classes: 108
 [proguard]   Final number of program classes:    99
 [proguard] Obfuscating...
 [proguard] Printing mapping to [D:\MY_PROJECT\bin\android\bin\deps\openfl_unityads\bin\proguard\mapping.txt]...
 [proguard] Writing output...
 [proguard] Preparing output jar [D:\MY_PROJECT\bin\android\bin\deps\openfl_unityads\bin\proguard\obfuscated.jar]
 [proguard]   Copying resources from program jar [D:\MY_PROJECT\bin\android\bin\deps\openfl_unityads\bin\proguard\original.jar]
 [proguard]   Copying resources from program jar [D:\MY_PROJECT\bin\android\bin\deps\extension-api\bin\classes.jar]
 [proguard] Warning: can't write resource [META-INF/MANIFEST.MF](Duplicate zip entry [classes.jar:META-INF/MANIFEST.MF])
 [proguard]   Copying resources from program jar [D:\MY_PROJECT\bin\android\bin\deps\openfl_unityads\libs\unity-ads.jar]
 [proguard] Warning: can't write resource [META-INF/MANIFEST.MF](Duplicate zip entry [unity-ads.jar:META-INF/MANIFEST.MF])

BUILD FAILED
C:\Development\Android_SDK\tools\ant\build.xml:597: The following error occurred while executing this line:
C:\Development\Android_SDK\tools\ant\build.xml:871: Can't write [D:\MY_PROJECT\bin\android\bin\deps\openfl_unityads\bin\proguard\obfuscated.jar] Can't read [D:\MY_PROJECT\bin\android\bin\deps\openfl_unityads\libs\unity-ads.jar] Duplicate zip entry [unity-ads.jar:com/unity3d/ads/android/BuildConfig.class]

Total time: 28 seconds
Build halted with errors.
Done(1)

**Comment by shadowofsoul** [comment]
hard to diagnose, but seems to be a permission problem at writing in the disk:

```
  Can't write D:\MY_PROJECT\bin\android\bin\deps\openfl_unityads\bin\proguard\obfuscated.jar
```

Could you comment the `<haxelib name="openfl-unityads" />` together with all the unityAds code you made, and try to make a clean build. if it doesn't compile, this is not related to the extension, is a local permission disk error in your side.

If it compiles, can you upload the project somewhere to test it here and give it a look? 

Let me know.

**Comment by xmorpher** [comment]
Ok, l'll try...
i'm compiling on windows so i didn't changed any disk permissions
but in the last line it says:
BUILD FAILED
C:\Development\Android_SDK\tools\ant\build.xml:597: The following error occurred while executing this line:
C:\Development\Android_SDK\tools\ant\build.xml:871: Can't write [D:\MY_PROJECT\bin\android\bin\deps\openfl_unityads\bin\proguard\obfuscated.jar] Can't read [D:\MY_PROJECT\bin\android\bin\deps\openfl_unityads\libs\unity-ads.jar] Duplicate zip entry [unity-ads.jar:com/unity3d/ads/android/BuildConfig.class]

**Comment by shadowofsoul** [comment]
i see it, but if the jar would be duplicated, there should be a duplicate class error. i still think this is a disk read/write error from you side. But i'm here to help you with further info :+1:

**Comment by xmorpher** [comment]
Thanks, i'll try with a clean project...

**Comment by xmorpher** [comment]
Shadowofsoul said: "i see it, but if the jar would be duplicated, there should be a duplicate class error. "
it says this: 
[proguard] Note: duplicate definition of program class [com.unity3d.ads.android.BuildConfig]

## Note: there were 1 duplicate class definitions Reading program jar [D:\MY_PROJECT\bin\android\bin\deps\openfl_unityads\libs\unity-ads.jar

What versions are you using for lime/openfl/googleplay/hxcpp/etc?
could you post a "haxelib list" print please?

**Comment by shadowofsoul** [comment]
I usually develop with this versions (old branches):

akifox-transform: [2.2.0]
devicelanguage: [1.0.0]
gamecenter: 1.0.1 [1.1.1]
golems: [1.2.2]
haxe-gif: [0.3.3]
haxelib_client: 3.1.0-rc.4 [3.2.0-rc.3]
hxcpp: 3.1.37 3.1.39 3.1.48 3.1.68 3.2.102 [3.2.81]
iap: 1.0.4 [1.0.6]
lime-tools: 1.4.0 1.5.6 [1.5.7]
lime: 0.9.7 1.0.0 1.0.1 2.0.1 2.0.3 2.1.0 2.1.1 2.1.3 2.3.1 2.3.3 2.4.1 [2.4.4]
nme-dev:
nme:
openfl-admob: 1.2.1 [1.3.2]
openfl-bitfive: 2.0.0 [2.1.6]
openfl-gpg: 1.0.0 [1.1.0]
openfl-gps-lib: 1.0.1 [1.0.2]
openfl-html5: [1.4.2-beta]
openfl-native: [1.4.0]
openfl-samples: 1.3.0 [3.1.0]
openfl-share: [1.1.0]
openfl-unityads: 1.0.1 1.0.3 1.0.4 [1.0.5]
openfl: 1.4.0 2.0.0 2.0.1 2.1.7 2.1.8 2.2.5 2.2.6 2.2.8 3.0.1 3.0.3 3.0.6 [3.1.0]

and works, BUT, i just updated everything, and it not only compiles with the latest version of hxcpp, openfl and lime, but also, it works on devices as expected.

actuate: [1.8.2]
akifox-transform: [2.2.0]
devicelanguage: [1.0.0]
gamecenter: 1.0.1 [1.1.1]
golems: [1.2.2]
haxe-gif: [0.3.3]
haxelib_client: 3.1.0-rc.4 [3.2.0-rc.3]
hxcpp: 3.1.37 3.1.39 3.1.48 3.1.68 3.2.102 [3.2.193] 3.2.81
iap: 1.0.4 [1.0.6]
lime-tools: 1.4.0 1.5.6 [1.5.7]
lime: 0.9.7 1.0.0 1.0.1 2.0.1 2.0.3 2.1.0 2.1.1 2.1.3 2.3.1 2.3.3 2.4.1 2.4.4 [2.7.0]
nme-dev:
nme:
openfl-admob: 1.2.1 [1.3.2]
openfl-bitfive: 2.0.0 [2.1.6]
openfl-gpg: 1.0.0 [1.1.0]
openfl-gps-lib: 1.0.1 [1.0.2]
openfl-html5: [1.4.2-beta]
openfl-native: [1.4.0]
openfl-samples: 1.3.0 [3.1.0]
openfl-share: [1.1.0]
openfl-unityads: 1.0.1 1.0.3 1.0.4 [1.0.5]
openfl-webview: [1.0.0]
openfl: 1.4.0 2.0.0 2.0.1 2.1.7 2.1.8 2.2.5 2.2.6 2.2.8 3.0.1 3.0.3 3.0.6 3.1.0 [3.4.0]

so, if you didn't copied or moved the jar somewhere else as it default install from haxelib, you have a permission problem of some kind.

**Comment by shadowofsoul** [comment]
like there was no more news about this, i'll be closing it.
