### ISSUE TITLE
Problem with Proguard

### ISSUE THREAD

**Issue by andrew-git** [ipsilondev/openfl-unityads#5]
When trying to build android target with latest (1.0.7) version openfl-unityads, I got

> Can't read [/PATH/TO/unity-ads.jar]  ( Can't process class [com/unity3d/ads/android/cache/UnityAdsCacheThread.class] (15360))

Looks like related to old issue https://github.com/ipsilondev/openfl-unityads/issues/3

I found same error topic on unity forum (http://forum.unity3d.com/threads/android-error-when-building-in-release-proguard-related.384812/)
and working receipt from it:

> commenting out the following line in the project.properties in unity-ads:
>     proguard.config=${sdk.dir}/tools/proguard/proguard-android.txt:proguard-project.txt

Not sure if it totally correct, but seems working.

Thanks

**Comment by shadowofsoul** [comment]
Yes, actually, i faced this same problem with building my latest game. And i solved in the same way. i haven't updated the repo why after contacting Unity, they told me to try to compile directly from source and not using the .jar. so in the near future, i'd like to give it a try and see if that fix the problem and enables pro-guard anyway. Still, they told me that ads will work and is not a violation of the ToS to disable it for now.

**Comment by andrew-git** [comment]
Thanks, will be waiting for news.
Maybe add temporarily notice to documentation, to help peoples solve problem if it appear?

**Comment by shadowofsoul** [comment]
Done :)
