### ISSUE TITLE
onVideoCompleted specification

### ISSUE THREAD

**Issue by andrew-git** [ipsilondev/openfl-unityads#6]
In integration guide for android (http://unityads.unity3d.com/help/monetization/integration-guide-android) onVideoCompleted listener has 2nd parameter skipped

> onVideoCompleted(String itemKey, boolean skipped) listener
> **If skipped is false, the player has watched an ad, and should be rewarded.**

In documentation for your extension you wrote

> ```
>    UnityAds.onVideoCompleted = function(key:String,reward:Bool):Void {
>         Lib.trace("onVideoCompleted = "+key+" = "+reward);
>     };
> ```

Second parameter named "reward" and so have opposite meaning.
Is it mistake (and better correct and rename accordingly to unity documentation) or you revert returning value inside your extension?

Thanks for extension and your work!

**Comment by shadowofsoul** [comment]
no, the value is directly passed from unityAds SDK to the callback function. thanks for the notice, i will change the name of the variable on next release, i suppose they changed that at some point and i never realized it.

**Comment by andrew-git** [comment]
Thanks!
